use_modular_headers!

platform :ios, '9.0'

target 'FYFWebController_Example' do
  pod 'FYFWebController', :path => '../'

  target 'FYFWebController_Tests' do
    inherit! :search_paths

    
  end
end
